### ISSUE TITLE
Slice bounds out of range panic

### ISSUE THREAD

**Issue by GauravRajSharma** [zix99/rare#10]
I tried the following filter for my log parsing.
```bash
rare h -b  -m "\[(INFO)|(ERROR)|(WARNING)|(CRITICAL)\]" *.log  -R
```
And rare threw the following panic.

![Screen Shot 2019-11-18 at 17 19 41](https://user-images.githubusercontent.com/16515861/69049386-d7475500-0a27-11ea-8a9f-26639b7609f6.png)

**Comment by zix99** [comment]
Definitely a real issue (and will fix with #11 once I add some more tests). Thanks!
