### ISSUE TITLE
float not supported?

### ISSUE THREAD

**Issue by alperyilmaz** [zix99/rare#102]
I wanted to draw a histogram for float values but I got `BAD-TYPE` error. Are decimal values not supported at all or do we need to process them with a trick?

Integer values work:
```
$ echo -e "1\n10\n15\n20" | rare h -e "{bucket {0}  10}"
10                  2
20                  1
0                   1

Matched: 4 / 4 (Groups: 3)
11 B (0 B/s) | <stdin>
```

But when I use decimal values, I get error
```
 echo -e "1.5\n10.2\n15.5\n20.0" | rare h -e "{bucket {0}  10}"
<BAD-TYPE>          4

Matched: 4 / 4 (Groups: 1)
19 B (0 B/s) | <stdin>
```

**Comment by zix99** [comment]
I'd have to double-check, but it seems like `bucket` only supports int (generally working with int's can be faster).

A quick hack for you would be to round/floor/ceil the number like: `{bucket {floor {0}} 10}`

**Comment by alperyilmaz** [comment]
looks like it's the `bucket` causing the problem.. in that case I can use some hacks.. 
Kudos for such great software, it's simply amazing..
