### ISSUE TITLE
Sort heatmap columns numerically

### ISSUE THREAD

**Issue by obaudys** [zix99/rare#80]
First off,  great work with the heatmaps feature! 

I've been using heatmaps for numerical data, in particular nginx response times.  I usually convert them it integers in rare by matching eg `0.053`  (seconds)  with `(\d+)\.(\d{3})` and then using the expression `{sumi {multi {1} 1000} {3}}` to convert to milliseconds.  

I've found that the table and heatmap sort the column names as strings, and not numerically if possible.  The results in meaningless heatmaps:
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/53287664/188046228-ed447d49-64fb-44ba-a279-2254b6ef9857.png">

I made a small change to a local checkout of rare to basically test if the column headers could be converted to integers and then sort them numerically if they can:
```diff
index 1be0be8..040b889 100644
--- a/pkg/aggregation/table.go
+++ b/pkg/aggregation/table.go
@@ -103,8 +103,23 @@ func (s *TableAggregator) OrderedColumns() []string {
 func (s *TableAggregator) OrderedColumnsByName() []string {
        keys := s.Columns()
 
+       // check if keys can be sorted numerically:
+       numeric := true
+       for _,k := range keys {
+               if _, err := strconv.Atoi(k); err != nil {
+                       numeric = false
+                       break
+               }
+       }
+
        sort.Slice(keys, func(i, j int) bool {
-               return keys[i] < keys[j]
+               if numeric {
+                       k0, _ := strconv.Atoi(keys[i])
+                       k1, _ := strconv.Atoi(keys[j])
+                       return k0 < k1
+               } else {
+                       return keys[i] < keys[j]
+               }
        })
 
        return keys

``` 
The same heatmap is now much more meaningful:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/53287664/188046876-701faad6-9b0b-4ea7-b746-bd118987036d.png">

Would you be interested in incorporating the above diff into rare?

**Comment by zix99** [comment]
Hey, thanks for the feedback!  Normally, I'd accept a diff like this very quickly.  I'm currently working on display-sorting with #79 which completely overhauls sorting across all aggregators, and implements things like: string, by-value, numeric, date-parsing, etc.  This also standardizes the sorting (Right now, sorting is slightly different on different aggregators, which only adds to the confusion)

You're welcome to check it out and see if it suits your needs (If not, let me know!)  It's not quite ready to merge yet, I want to add the ability to sort rows and cols separately, as well as add documentation.

**Comment by obaudys** [comment]
I've checked out the sorting branch.   Heatmaps for my use case (response latencies) work out of the box for me with the "smart" sorting method.  Thanks heaps for the awesome work!  The code is a bit hard for me to understand, eg. what does by-value sorting actually mean?  Make sure you include that in the documentation!

**Comment by zix99** [comment]
Glad it works for you!

I'll definitely include definitions in the docs.. I haven't landed on the exact naming yet, so it might change once I merge.
