### ISSUE TITLE
Memory and CPU usage

### ISSUE THREAD

**Issue by proyb6** [zix99/rare#9]
I'm curious the Readme could included the memory and CPU usage between standard unix tools ga and rare?

Another take to benchmark on embedded device is useful.

**Comment by zix99** [comment]
I'll try to formalize something soon, but for now here's some comments:
I ran pprof on 800 MB of nginx log files with the same match as the cpu-time tests in the readme.  I tweaked the code to store the entire search in memory and saw what I expected (~800MB of data).

When running rare under normal conditions and taking profiling heap snapshots, I saw ~4 MB of allocated heap objects.  Over time, it allocated a total of around 1.1 GB of objects (Which is in-line with expectation in terms of data size).

![image](https://user-images.githubusercontent.com/1558302/69206941-2d95c000-0b1c-11ea-9cbc-9cb16bf54195.png)
