### ISSUE TITLE
Is there a way to sort histogram in reverse order?

### ISSUE THREAD

**Issue by agzam** [zix99/rare#95]
Here's for example a snippet that shows a histogram, tracking monthly changes in a git repo:

    git log --first-parent --pretty=format:"%ad%x09%s" --date="format:%Y-%m" | \
    awk '{ print $1 }' | rare histogram -a --sort date
    
It spits out something like: 

    2021-10             10         [ 4.6%] ████████████
    2021-11             42         [19.3%] ██████████████████████████████████████████████████
    2021-12             8          [ 3.7%] █████████▌
    2022-01             4          [ 1.8%] ████▊
    2022-02             7          [ 3.2%] ████████▍
    2022-03             2          [ 0.9%] ██▍
    2022-04             19         [ 8.7%] ██████████████████████▋
    2022-05             3          [ 1.4%] ███▋
    2022-06             9          [ 4.1%] ██████████▊
    2022-07             7          [ 3.2%] ████████▍
    2022-08             4          [ 1.8%] ████▊
    2022-09             10         [ 4.6%] ████████████
    2022-10             15         [ 6.9%] █████████████████▉
    2022-11             27         [12.4%] ████████████████████████████████▏
    2022-12             3          [ 1.4%] ███▋
    2023-01             5          [ 2.3%] ██████
    2023-02             10         [ 4.6%] ████████████
    2023-03             8          [ 3.7%] █████████▌
    2023-04             8          [ 3.7%] █████████▌
    2023-05             11         [ 5.0%] █████████████
    2023-06             6          [ 2.8%] ███████▏
    
Now, how can I get it sorted in descending order? I can't use cmd-line `sort`, it breaks the histogram.

**Comment by zix99** [comment]
I think you want to add the `:reverse` modified like `--sort date:reverse`

See [the sorting docs](https://rare.zdyn.net/usage/aggregators/#sorting) for more details.

Is that what you're looking for?

**Comment by agzam** [comment]
Thank you. Apologies for the noise. I just found this awesome tool and couldn't figure it out.
